spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  mybatis:
    mapper-locations: classpath*:mapper/**/*.xml
    type-aliases-package: com.nareumadmin.domain
    configuration:
      jdbc-type-for-null: VARCHAR  # 이거 없으면 mybatis로 null 값을 넣을 수 없음
      map-underscore-to-camel-case: true
      default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

server:
  port: 8081