spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://54.180.79.241:3306/nareum_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: nareumadmin!
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  mybatis:
    mapper-locations: classpath*:mapper/**/*.xml
    type-aliases-package: com.nareumadmin.domain
    configuration:
      jdbc-type-for-null: VARCHAR  # 이거 없으면 mybatis로 null 값을 넣을 수 없음
      map-underscore-to-camel-case: true
      default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

logging:
  level:
    org.mybatis: DEBUG
    org.apache.ibatis: TRACE

server:
  port: 8081